name: vidl_viz

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3
  - numpy
  - pandas
  - scipy
  - seaborn>=0.8.1
  - pip
  - bokeh
  - wordcloud
  - missingno
  - pydotplus
  - shapely
  - descartes
  - graphviz